# Importando biblioteca

In [2]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4,5,6],[3,4,5,6,7,8]])
print(a)
print(type(a))

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
<class 'numpy.ndarray'>


### np.zeros

#### np.zeros(shape = (numero de array, numero de linhas, numero de colunas))

In [6]:
zero_array = np.zeros(shape = (5, 3, 5))
print(zero_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


### np.ones((numero de linhas, numero de colunas))

In [8]:
um_array = np.ones((2, 3))
print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


### np.empty((numero de linhas, numero de colunas))

In [12]:
vazio_array = np.empty((3, 4))
print(vazio_array)

[[1.22173506e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.29441743e-312 2.10775999e-052 5.99196711e-066 6.59758894e-042]
 [4.75375926e+174 3.92270269e+179 5.80154213e+170 1.74416871e-076]]


### np.arange(começo, fim, intervalo)

In [18]:
arr = np.arange(50, 200, 30)
arr1 = np.arange(step = 30, start = 50, stop = 200)
print(arr)
print()
print(arr1)

[ 50  80 110 140 170]

[ 50  80 110 140 170]


### np.linspace(inicio, fim, quantidade de numeros, numeros depois da virgula, intervalo )

In [22]:
array_linear = np.linspace(0, 100, num = 20, endpoint = False)
array_linear1 = np.linspace(0, 100, num = 20, endpoint = True, retstep = True)
print(array_linear)
print()
print(array_linear1)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.
 90. 95.]

(array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ]), 5.2631578947368425)


### Descobrindo o tamanho de um Array

In [23]:
zero_array = np.zeros(shape = (5, 3, 5))
print(zero_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [25]:
print(zero_array.shape)
print(zero_array.size)
print(zero_array.ndim)

(5, 3, 5)
75
3


### Transformando um vetor(1-D) em uma matriz(2-D)

In [27]:
a = np.array([1,2,3])
print(a.ndim)

1


#### Da vertical para horizontal

In [28]:
a21 = a[np.newaxis,:]
print(a21.shape)
print(a21.ndim)
print(a21)

(1, 3)
2
[[1 2 3]]


#### Da horizontal para vertical

In [29]:
a22 = a[:,np.newaxis]
print(a22.shape)
print(a22.ndim)
print(a22)

(3, 1)
2
[[1]
 [2]
 [3]]


#### Acessando dados especifico da array

In [31]:
print(a22[0][0])
print(a22[1][0])

1
2


#### Concatenando arrays

In [32]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
d = np.concatenate((b,a))

print(c)
print(d)

[1 2 3 4 5 6]
[4 5 6 1 2 3]


#### Consultando itens de uma array (de uma forma especifica)

In [37]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print()
maior_8 = a[a > 8]
menor_8 = a[a < 8]
div_2 = a[a % 2 == 0]

print(f'Maiores que 8: {maior_8}')
print(f'Menores que 8: {menor_8}')
print(f'Divisiveis por 2: {div_2}')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Maiores que 8: [ 9 10 11 12]
Menores que 8: [1 2 3 4 5 6 7]
Divisiveis por 2: [ 2  4  6  8 10 12]


## Operações com arrays:
####  Soma
####  Minimo
####  Maximo
###  Media

In [38]:
a = np.array([1,2,3])
print(f'A soma: {a.sum()}')
print(f'O maximo: {a.max()}')
print(f'O minimo: {a.min()}')
print('{a.mean()}')

6
3
1
2.0


### Gerando amostras aleatorias

In [1]:
from numpy.random import default_rng

In [5]:
rng = default_rng()
aleatorio = rng.integers(20, size = (2, 4))
print(aleatorio)

[[ 1  2 18 11]
 [ 5  3 10  6]]


#### Diferenca entre Array e Listas
##### Array - Permite apenas um tipo de dados
##### List - Permite mais de um tipo de dados

In [14]:
import numpy as np
a = np.array([1,'imr',3,4,5,7,8])
print(f'Transformou todos dados em strings \n{a}')
print(type(a))
print()
list_a = [1,'imr',3,4,5,7,8]
print(list_a)
print(type(list_a))

Transformou todos dados em strings 
['1' 'imr' '3' '4' '5' '7' '8']
<class 'numpy.ndarray'>

[1, 'imr', 3, 4, 5, 7, 8]
<class 'list'>


## Comparando o processamento


#### Usando lista

###### A lista não consegue multiplicar uma grande quantidade de numeros

In [17]:
from time import process_time
list_a = list(rng.integers(10, 100, 10000000))
list_b = list(rng.integers(10, 100, 10000000))
#print(type(list_a))
c = []
c = list_a * list_b

TypeError: can't multiply sequence by non-int of type 'list'

##### Com 'for', ela calcula, mas demora

In [22]:
c = []
t1 = process_time()
for i in range(len(list_a)):
    c.append(list_a[i] * list_b[i])
t2 = process_time()
print(t2 - t1)

4.03125


#### Usando Array

In [29]:
a = rng.integers(10, 100, 10000000)
b = rng.integers(10, 100, 10000000)

t1a = process_time()
c = a * b
t2a = process_time()
print(t2a - t1a)

0.046875


In [ ]:
import matplotlib as plt

dados_x = rng.integers(20, size = 30)
dados_y = rng.integers(12, size = 30)

#plt.scatter(x = dados_x, y = dados_y)
#plt.show()